export const SCREEN_LIST = {
  HOME: 'Home',
  SEARCH: 'Search',
  NOTIFICATION: 'Notification',
  PROFILE: 'Profile',
  EDIT_PROFILE: 'EditProfile',
  LIST_PLANT_POT: 'ListPlantPot',
  LIST_TOOL: 'ListTool',
  LIST_PLANT: 'ListPlant',
  PRODUCT_DETAIL: 'ProductDetail',
  QUESTION_AND_ANSWER: 'QuestionAndAnswer',
  TUTORIAL_LIST: 'TutorialList',
  TUTORIAL_DETAIL: 'TutorialDetail',
  ORDER_HISTORY: 'OrderHistory',
  ORDER_DETAIL: 'OrderDetail',
  SHOPPING_CART: 'ShoppingCart',
  CHECKOUT: 'Checkout',
  PAYMENT_INFORMATION: 'PaymentInformation',
  ORDER_SUCCESSFUL: 'OrderSuccessful',
};
